/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Qbittorrent webapi /api/v2/sync/maindata response.
 */
export interface MaindataResponse {
  /**
   * Response ID
   */
  rid: number;
  /**
   * Whether the response contains all the data or partial data
   */
  full_update: boolean;
  server_state?: TransferInfoResponse;
  /**
   * Dictionary of torrent-hash against torrent-attributes
   */
  torrents?: {
    [k: string]: TorrentInfo;
  };
  [k: string]: unknown;
}
/**
 * Qbittorrent webapi /api/v2/transfer/info response.
 */
export interface TransferInfoResponse {
  /**
   * Data downloaded this session (bytes)
   */
  dl_info_speed: number;
  /**
   * Whether the response contains all the data or partial data
   */
  connection_status: 'connected' | 'firewalled' | 'disconnected';
  [k: string]: unknown;
}
/**
 * Qbittorrent webapi Torrent Info
 */
export interface TorrentInfo {
  /**
   * Torrent name
   */
  name: string;
  /**
   * Torrent progress (percentage/100)
   */
  progress: number;
  [k: string]: unknown;
}
